name: Update Documentation

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  

jobs:
  get-docs:
    runs-on: ubuntu-latest
    outputs:
      changes_made: ${{ steps.commit.outputs.changes_made }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
   
      - name: Clone
        run: |
          git clone https://github.com/aoijs/website.git temp-website-repo

      - name: Create
        run: |
          echo "Creating directories"
          mkdir -p ./scripts/docs/functions
          mkdir -p ./scripts/docs/canvas
          mkdir -p ./scripts/docs/music

      - name: Copy
        run: |
          echo "Copying 'aoi.canvas function docs' to current repo"
          cp -r temp-website-repo/src/content/docs/extensions/@aoijs/aoi.canvas/functions/* ./scripts/docs/canvas/
          echo "Copied canvas functions"
          echo "Copying 'aoi.music function docs' to current repo"
          cp -r temp-website-repo/src/content/docs/extensions/@aoijs/aoi.music/music/* ./scripts/docs/music/
          echo "Copied music functions"
          echo "Copying 'aoi.js function docs' to current repo"
          cp -r temp-website-repo/src/content/docs/functions/* ./scripts/docs/functions/
          echo "Copied function docs (main)"

      - name: Cleanup
        run: |
          rm -rf temp-website-repo
          
      - name: Commit
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "[workflow] Update documentation"
            git push origin main
            echo "::set-output name=changes_made::true"
          else
            echo "No changes to commit"
            echo "::set-output name=changes_made::false"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-functions:
    runs-on: ubuntu-latest
    needs: get-docs
    if: needs.commit.outputs.changes_made == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run
        run: cd scripts && node extract.js

      - name: Clone aoijs-api repository
        run: |
          git clone https://github.com/faf4a/aoijs-api.git temp-api-repo

      - name: Compare functions.json
        run: |
          if ! diff -q scripts/functions.json temp-api-repo/src/pages/assets/data/functions.json; then
            echo "Files are different. Proceeding with update."
          else
            echo "No differences found. Skipping PR creation."
            exit 0
          fi

      - name: Update functions.json in aoijs-api
        run: |
          cp scripts/functions.json temp-api-repo/src/pages/assets/data/functions.json
          echo "normal"
          ls
          cd temp-api-repo
          echo "changed"
          ls
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add src/pages/assets/data/functions.json
          git commit -m "[workflow] Update functions.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request to aoijs-api
        run: |
          cd temp-api-repo
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/faf4a/aoijs-api.git
          git push origin master:refs/heads/update-functions
          gh pr create --title "[workflow] Update functions.json" --body "hello, i am a bot! please merge the api changes." --repo faf4a/aoijs-api --head update-functions --base master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Notify Discord of PR success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "meow <@428188716641812481>, please confirm the [api changes](https://github.com/faf4a/aoijs-api/pulls)!"}' \
          ${{ secrets.DISCORD_WORKFLOW }}
