name: Download Documentation

on:
  workflow_dispatch:

jobs:
  get-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
   
      - name: Clone
        run: |
          git clone https://github.com/aoijs/website.git temp-website-repo

      - name: Create
        run: |
          echo "Creating directories"
          mkdir -p ./scripts/docs/functions
          mkdir -p ./scripts/docs/canvas
          mkdir -p ./scripts/docs/music

      - name: Copy
        run: |
          echo "Copying 'aoi.canvas function docs' to current repo"
          cp -r temp-website-repo/src/content/docs/extensions/@aoijs/aoi.canvas/functions/* ./scripts/docs/canvas/
          echo "Copied canvas functions"
          echo "Copying 'aoi.music function docs' to current repo"
          cp -r temp-website-repo/src/content/docs/extensions/@aoijs/aoi.music/music/* ./scripts/docs/music/
          echo "Copied music functions"
          echo "Copying 'aoi.js function docs' to current repo"
          cp -r temp-website-repo/src/content/docs/functions/* ./scripts/docs/functions/
          echo "Copied function docs (main)"

      - name: Cleanup
        run: |
          rm -rf temp-website-repo
          
      - name: Commit
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          git commit -m "[workflow] Update documentation"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-functions:
    runs-on: ubuntu-latest
    needs: get-docs

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run
        run: cd scripts && node script.js

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add docs/functions.json
          git commit -m "[workflow] Update functions" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
